language: node_js
node_js:
  - "4.4.5"

before_install:
  - git config --global push.default matching
  - git config --global user.name "xiao-fang"
  - git config --global user.email "xiao.fang@outlook.com"
  - npm install hexo-cli -g

install:
  - npm install --save

script:
  - hexo clean
    # - hexo algolia
  - hexo generate

after_success:
  #- hexo d
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "auto build & deployed via Travis on `date`"
  - git push --quiet --force https://$GH_DEPLOY_TOKEN@github.com/xiao-fang/xiao-fang.github.io.git master
  - cd ..
  - rm -rf ./.deploy_git
  - rm -rf ./public

branches:
  only:
    - hexo
cache:
  directories:
    - node_modules
