language: node_js
node_js:
  - "4.4.5"

before_install:
  - git config --global push.default matching
  - git config --global user.name "xiao-fang"
  - git config --global user.email "xiao.fang@outlook.com"

install:
  - npm install hexo-cli -g
  - npm install hexo --save
  - npm install
  - npm install hexo-deployer-git --save
  - npm install hexo-generator-archive --save
  - npm install hexo-generator-category --save
  - npm install hexo-generator-feed --save
  - npm install hexo-generator-index --save
  - npm install hexo-generator-tag --save
  - npm install hexo-renderer-ejs --save
  - npm install hexo-renderer-jade --save
  - npm install hexo-renderer-marked --save
  - npm install hexo-renderer-stylus --save
  - npm install hexo-toc --save
  - npm install hexo-util --save

script:
  - hexo clean
  - hexo generate

after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "auto build & published via Travis CI on `date`"
  - git push --quiet --force https://$DEPLOY_REPO_TOKEN@github.com:xiao-fang/xiao-fang.github.io.git master
  - rm -rf ../.deploy_git
  - rm -rf ..

branches:
  only:
    - master
cache:
  directories:
    - node_modules