language: node_js
node_js:
  - "4.4.5"

before_install:
  - git config --global push.default matching
  - git config --global user.name "xiao-fang"
  - git config --global user.email "xiao.fang@outlook.com"
  - npm install hexo-cli -g

install:
  - npm install --save

script:
  - hexo clean
  - hexo generate

after_success:
  - hexo d
  - rm -rf ../.deploy_git
  - rm -rf ..
  - ll

branches:
  only:
    - master
cache:
  directories:
    - node_modules