title: xiao-fang.me
subtitle: Hello Edward
description: trust your heart / if the seas catch fire / and live by love / though the stars walk backward
author: Xiao Fang, xiao.fang@outlook.com

avatar: https://s.gravatar.com/avatar/1d49cc3c20c76d2b3aaece97f80bab75?s=80

twitter:
rss: atom.xml
weibo: vanceeshaw
instagram:

# Comment
duoshuo: xx
disqus: xxxx